### ISSUE TITLE
Starting the udt server in the sample section drops exception

### ISSUE THREAD

**Issue by MiklosPathy** [PlasticSCM/UdtSharp#7]
If i simply start the project with options "udt server 9000" it drops an exception:

Unhandled exception. System.Exception: Problem when listening with 5
 ---> UdtSharp.UdtException: Operation not supported: Listen/accept is not supported in rendezous connection setup
   at UdtSharp.UdtUnited.listen(Int32 u, Int32 backlog) in C:\Users\mpathy\Desktop\UDT\UdtSharp-master\src\UdtUnited.cs:line 385
   at UdtSharp.UdtSocket.Listen(Int32 maxConnections) in C:\Users\mpathy\Desktop\UDT\UdtSharp-master\src\UdtSocket.cs:line 56

**Comment by snltty** [comment]
me too，did you fix it？

**Comment by wch1618** [comment]
I download the source code and changed from `m_bRendezvous = false` to `m_bRendezvous = true` in `public UDT()` of src\Core.cs, the sample work
